### ISSUE TITLE
Proposal: Support `BuildInsert` receive the struct rather than map[string]interface{}

### ISSUE THREAD

**Issue by xiekeyi98** [didi/gendry#103]
Thanks for this fantastic repo.

Now, We use `scanner.ScanClose( rows , interface{} )` , and use reflect (tagName: `ddb` ) to fill the interface.
And use the `builder.BuildInsert( map[string]interface{} ) ` to build the insert sql.

In my humble opinion, I think it is not consistent.

Shall we can support some function signed as ` builder.BuildInsert( interface{} ) ` , And We could transfer `interface{}` to `map[string]interface{}` by reflect.

For example:
```golang

func ToMap(in interface{}, tagName string) (map[string]interface{}, error){
	out := make(map[string]interface{})

	v := reflect.ValueOf(in)

	t := v.Type()

	for i := 0; i < v.NumField(); i++ {
		fi := t.Field(i)
		if tagValue := fi.Tag.Get(tagName); tagValue != "" {
			out[tagValue] = v.Field(i).Interface()
		}
	}
	return out, nil
}
```

In this case, we could use `builder.BuildInsert( TheStructWithDDBtag )`.
Maybe it will more consistent and convenient.

How about this?

If you don't mind, I'm glad to try to implement this feature.

**Comment by caibirdme** [comment]
The main reason I make the input as `map[string]interface{}` is that it's easy to use and expressive. Changing the function signature will be a huge breaking change, I don't think the `consistency` is a good enough reason to make that change.
I got your point but I don't know why you prefer using a struct rather than just a simple map. Can you give me some use cases? Why struct is more convenient, what's the benefit? Thx

**Comment by xiekeyi98** [comment]
Thanks for your reply.

I do not mean to make the **breaking change**, maybe we could support more functions which signed as "interface{}".

I think this is convenient because as the example below:

```golang
type Person struct {
	Name string `ddb:"name"`
	Age int `ddb:"m_age"`
}

rows, err := db.Query("SELECT age as m_age, name from g_xxx where xxx")
defer rows.Close()

var students []Person

scanner.Scan(rows, &students)
```
Usually, we use the struct with the tag `ddb`, and call `scanner.Scan` to fill the struct.

For consistency, it is obvious and easy to use the same struct with BuildInsert with `ddb` tag.

IMHO, If we call `Insert` with `map[string]interface{}` frequently in different places , it's easy to generate a lot of string constants that look like magic numbers.

If we use constructs, we can make good use of type checking and easy to fill the struct.

This is the demo of how to use:

```golang

 newRecord := Person{ Name: "Test" , Age: 10 };

AddRecordFromStruct(newRecord);


func  AddRecordFromStruct(values interface{}) (num int64, err error) {
	mp, err := ToMapForInsert(values)
	if err != nil {
		……
	}

	return addRecord(mp)

}

func  addRecord(values map[string]interface{}) (num int64, err error) {


	db, err := getDBHandler()

	if err != nil {
              ……
	}

	var data []map[string]interface{}
	data = append(data, values)

	cond, vals, err := builder.BuildInsert(TableName, data)
	if err != nil {
		……
	}

	res, err := db.Exec(cond, vals...)
	if err != nil {
		……
	}
	return res.LastInsertId()

}

func ToMapForInsert(in interface{}) (map[string]interface{}, error) {
	return toMap(in, "ddb")
}
func toMap(in interface{}, tagName string) (map[string]interface{}, error) {
	out := make(map[string]interface{})

	v := reflect.ValueOf(in)

	if v.Kind() == reflect.Ptr {
		v = v.Elem()
	}
	if v.Kind() != reflect.Struct {
		……
	}

	t := v.Type()

	for i := 0; i < v.NumField(); i++ {
		fi := t.Field(i)
		if tagValue := fi.Tag.Get(tagName); tagValue != "" {
			out[tagValue] = v.Field(i).Interface()
		}
	}
	return out, nil
}


```

**Comment by caibirdme** [comment]
Maybe this will bring some other issues, like, what if I just want to insert part of struct not all the fields? How can I express the demand? If we enhance the tag instructions to solve this problem, but what if in some function I want to insert A B C of structT, while in another function I want to insert B C D of structT? So I think map might be the best way to express what you want to insert.
But I understand your thought. For me, it's ok to add some more helper functions in gendry, like `ToInsertMap(data interface{}, tagName string) map[string]interface{}`

**Comment by xiekeyi98** [comment]
Thanks for considering my idea.  These are only my simple immature thoughts I've encountered in the work.


Some codes will be added who used this repo are better, rather than make this repo coupling with business.

We should make the base library this repo simple and restraint.

**Comment by caibirdme** [comment]
Thx for your proposal, the discussion could make the project better :)
