### ISSUE TITLE
mysql预处理

### ISSUE THREAD

**Issue by yezongwen99** [didi/gendry#104]
请问下，这个库 支持 mysql预处理吗？

**Comment by caibirdme** [comment]
> 请问下，这个库 支持 mysql预处理吗？

你说的预处理是指prepare吗？这个和这个库没关系，你只要用标准库，默认都是会prepare的

**Comment by yezongwen99** [comment]
嗯嗯，知道了，谢谢。。。













在 2020-11-03 22:47:05，"Deen" <notifications@github.com> 写道：

请问下，这个库 支持 mysql预处理吗？

你说的预处理是指prepare吗？这个和这个库没关系，你只要用标准库，默认都是会prepare的
