### ISSUE TITLE
is null 和 is not null

### ISSUE THREAD

**Issue by aimuz** [didi/gendry#11]
is null 和 is not null 这样的应该怎样使用？

**Comment by caibirdme** [comment]
For now, you can do it by `NamedQuery`:
builder.NamedQuery(`select colA,colB,colC from tb where colA is not null and colB in {{some}}`, map[string]interface{}{
    "some": []int{1,3,5,7},
})

**Comment by caibirdme** [comment]
是的，按照我们的实践，复杂查询我们推荐应该直接写SQL，这样才不容易不错。NamedQuery帮助来把in的对象展开，相当于一个helper。
上面你说的我觉得还是有必要把这个feature加上，最终的效果如下:
```
where := map[string]interface{}{
	"city in": []interface{}{"beijing", "shanghai"},
	"score": 5,
	"age >": 35,
        "name": builder.ISNotNull,
        "address": builder.ISNull,
}
```
你觉得使用起来OK吗

**Comment by caibirdme** [comment]
@aimuz 这个功能已经加上

**Comment by aimuz** [comment]
good
