### ISSUE TITLE
builder.BuildSelect where参数传递的map[string]interface{}在生成sql的时候where顺序随机生成，导致生成sql不走索引

### ISSUE THREAD

**Issue by dangerous1990** [didi/gendry#115]
可以支持LinkedHashMap吗？

**Comment by caibirdme** [comment]
> 可以支持LinkedHashMap吗？

* where顺序不随机，是确定的，builder会对字段按照字典序排序
* 即使是随机顺序，mysql的优化器也会根据索引调整顺序，即——字段顺序不影响mysql对索引是使用
