### ISSUE TITLE
支持多个 or 查询

### ISSUE THREAD

**Issue by zhanghongnian** [didi/gendry#129]
支持多个 or 查询
`(A=1 OR B=2) AND (C=3 OR D=4)`

需求和这个 pr 一样 https://github.com/didi/gendry/pull/125 
换了一种实现方式 https://github.com/didi/gendry/pull/130
![image](https://user-images.githubusercontent.com/9982100/173273084-6a74d779-a0ce-4596-b3ec-97e794b28188.png)

**Comment by twz915** [comment]
https://github.com/didi/gendry/pull/125
