### ISSUE TITLE
 ORDER BY 多个排序条件

### ISSUE THREAD

**Issue by aimuz** [didi/gendry#17]
_orderby 是不是只支持单个排序字段呢？

我尝试这样使用
```
where := map[string]interface{}{
		"_orderby": "state,index_num asc",
}
```

出现了错误
`[builder] the value of _orderby should be "field direction"`

**Comment by caibirdme** [comment]
是的，目前只支持单个字段，我尽快加入这个改进

**Comment by aimuz** [comment]
thx
