### ISSUE TITLE
builder.BuildInsert 生成的sql 报错了

### ISSUE THREAD

**Issue by vstTang** [didi/gendry#20]
cond, vals, err := builder.BuildInsert("testTable", data)
	if nil != err {
		return 0, err
	}
	result, err := db.Exec(cond, vals...)
最后执行  db.Exec(cond, vals...)的时候有错误产生  我用的是mysql
<error>
data:<*errors.errorString>
s:"sql: converting argument $1 type: unsupported type []map[string]...+28 more"

**Comment by caibirdme** [comment]
如果没有其它问题的话，我暂时先关闭这个issue了
