### ISSUE TITLE
scanner不支持sql.NullString, sql.NullInt64这些类型？

### ISSUE THREAD

**Issue by jacexh** [didi/gendry#25]
- NullString: https://golang.org/pkg/database/sql/#NullString

目前看上去并不支持这些类型，错误信息如下，是否能够支持这些特殊类型？

```
scanner.ScanErr{structName:"config", fieldName:"name", from:(*reflect.rtype)(0x7c5b00), to:(*reflect.rtype)(0x812b40)}
```

**Comment by caibirdme** [comment]
确实，现在还没有支持sql包里的NullXX类型，我会在接下来的一段时间考虑加上这块儿的支持（如果你感兴趣也欢迎Pr）。

我理解的话，你的需求是因为表中有字段可以为NULL，然后你希望有办法能够判断这个信息。我刚才提交了一个新的commit，应该可以支持你目前的需求，你只要把可以为NULL的字段设置为指针类型即可：
```
type struct User {
    Name *string `ddb:"name"`,
    Score *float64 `ddb:"rank"`,
}

var u User

scanner.Scan(rows, &u)
// 如果数据库中name字段为NULL
if u.Name == nil {
// 这里等价于NullString中的 if u.Valid == false
}
```
不过只要有指针，用的时候一定要记得判断if xx.YY !=nil 哦

**Comment by jacexh** [comment]
> @jacexh 确实，现在还没有支持sql包里的NullXX类型，我会在接下来的一段时间考虑加上这块儿的支持（如果你感兴趣也欢迎Pr）。
> 
> 我理解的话，你的需求是因为表中有字段可以为NULL，然后你希望有办法能够判断这个信息。我刚才提交了一个新的commit，应该可以支持你目前的需求，你只要把可以为NULL的字段设置为指针类型即可：
> 
> ```
> type struct User {
>     Name *string `ddb:"name"`,
>     Score *float64 `ddb:"rank"`,
> }
> 
> var u User
> 
> scanner.Scan(rows, &u)
> // 如果数据库中name字段为NULL
> if u.Name == nil {
> // 这里等价于NullString中的 if u.Valid == false
> }
> ```
> 不过只要有指针，用的时候一定要记得判断if xx.YY !=nil 哦

多谢，我随后试下
