### ISSUE TITLE
sql语句的查询问题

### ISSUE THREAD

**Issue by zhanghongming** [didi/gendry#32]
想知道可以把数据库字端和数据一一对应的返回吗？
目前看好像就是返回数据，我们自己解析到struct上

**Comment by caibirdme** [comment]
我没看明白你描述的需求，你可以给一段你期望的功能的伪代码
目前我们可以帮你映射到struct不需要你自己映射啊
```
row,err := db.Query(`select user_name,age from user where id>100`)

type User struct {
  Name string `ddb:"user_name"`
  Age int `ddb:"age"`
}

var students []User
scanner.Scan(rows, &students)
```
这样就行了

**Comment by zhanghongming** [comment]
对，目前就是这样的，我希望没有struct，而是自动返回数据库的字端，目前都是我把数据库的字端变成struct来解析的，感觉这样很麻烦

**Comment by zhanghongming** [comment]
//字段
	cols, _ := rows.Columns()
比如这个就可以

**Comment by caibirdme** [comment]
> 对，目前就是这样的，我希望没有struct，而是自动返回数据库的字端，目前都是我把数据库的字端变成struct来解析的，感觉这样很麻烦

@zhanghongming  我给的demo代码你还觉得用起来麻烦吗？那你现在的代码是什么样的呢，可以分享下么

**Comment by caibirdme** [comment]
@zhanghongming 你是指的ScanMap吗，比如：
```
rows, _ := db.Query("select name, age as m_age from person")
result, err := scanner.ScanMap(rows)
for _, record := range result {
	fmt.Println(record["name"], record["m_age"])
}
```
这个功能目前也是支持的
