### ISSUE TITLE
ScanMapDecode对string处理问题

### ISSUE THREAD

**Issue by MandssS** [didi/gendry#38]
hello ，
   我这边遇到一个问题，mysql的一个字段  eg: `user_name` varchar(50) NOT NULL DEFAULT '',  存在数据库的值是“string(nan)”，经过"github.com/didi/gendry/scanner" 中的ScanMapDecode方法，就会变成float64=NaN。我看你里面有会先将string转为[110 97 110]uint8，然后再转出float64(NaN)。想问下，当初你们这样设计是出于什么考虑呢

**Comment by caibirdme** [comment]
没太看懂你的问题，要不你贴一段代码，注释上你期望的结果和实际结果

**Comment by MandssS** [comment]
eg： id     user_name   字段的定义在最上面
         1       nan
 select user_name from a where id = 1;
        我希望得到的 string(nan)
        但是我最后得到的是float64(NaN)

**Comment by caibirdme** [comment]
了解了，这个是因为 [strconv这里做了特殊处理](https://golang.google.cn/src/strconv/atof.go?s=11079:11134#L52)。

> 我看你里面有会先将string转为[110 97 110]uint8，然后再转出float64(NaN)。想问下，当初你们这样设计是出于什么考虑呢

并没有将string转成[]uint8，而是go-sql-driver/mysql这个驱动返回的数据类型就是[]uint8，这里只是类型推断，不是类型转换。由于历史原因，驱动的不同版本对同一个mysql的数据类型可能返回不同的值，在某些版本bigint会使用[]byte来返回，因此这里需要类型推断到[]uint8（等价于[]byte），然后尝试进行类型转换。

目前看起来你面临的问题暂时是无法解决的，如果驱动不能保证所有数值类型从rows里读出来都是数值类型，那这里就得做这么一层转换。

解决方案是，你可以换成Scan方法，定义一个结构体，这样在进行类型转换时会按照你期望的类型来转换

**Comment by caibirdme** [comment]
If no more question, I will close the issue
