### ISSUE TITLE
builder support "not in" operator

### ISSUE THREAD

**Issue by althen** [didi/gendry#39]

**Comment by althen** [comment]
where := map[string]interface{}{
		"col not in":"id",
}
BuilderSelect(table,where,fields) 
error: [builder] unsupported operator

**Comment by caibirdme** [comment]
`not in` is not supported yet. I'll add that feature tomorrow. The workaround the solve this by now is using NamedQuery to write the sql manually

**Comment by caibirdme** [comment]
see this [commit](https://github.com/didi/gendry/commit/d498822d95d99b9f3d3e3d81b31aeeb717a1cc77)

**Comment by althen** [comment]
🎉   thanks
