### ISSUE TITLE
_orderby cant support function 

### ISSUE THREAD

**Issue by jingyugao** [didi/gendry#44]
for example:
      where := map[string]interface{}{
		"_orderby":          "IFNULL(I_VALUE,0) DESC, I_ID DESC",
		"_limit":            []uint{0, 1},
	}
	query, args, err := builder.BuildSelect("src_table", where, []string{"I_ID,I_VALUE"})
	if err != nil {
		return
	}
	err = db.Select(&ret, query, args...)

in this case,gendry will split the "," in function "IFNULL".

**Comment by jingyugao** [comment]
ok,I use column alias. Though not so convenient,it works.

**Comment by caibirdme** [comment]
> ```
> for example:
>   where := map[string]interface{}{
> 	"_orderby":          "IFNULL(I_VALUE,0) DESC, I_ID DESC",
> 	"_limit":            []uint{0, 1},
> }
> query, args, err := builder.BuildSelect("src_table", where, []string{"I_ID,I_VALUE"})
> if err != nil {
> 	return
> }
> err = db.Select(&ret, query, args...)
> ```
> 
> in this case,gendry will split the "," in function "IFNULL".

Sorry for the inconvenience. Gendry splits the comma for the sake of supporting grammar like this `colA asc,colB desc`. But if taking function call into consideration, it will become extremely complicated and hard to implement, we must parse it into an AST, by doing that can we understand the meaning of each parts. 
For sql like this, I recommend you'd better use builder.NamedQuery to write sql manually

**Comment by caibirdme** [comment]
One of the advantage of Gendry is that, it's non-intrusive. Which means if something gendry not support, you can write sql manually, which, in fact, won't cost you too much time . It just a tool which help you construct sql, and do nothing else.

**Comment by jingyugao** [comment]
> One of the advantages Gendry has is that, it's non-intrusive. Which means if something gendry not support, you can write sql manually, which, in fact, won't cost you too much time . It just a tool which help you construct sql, and do nothing else.

Thanks a lot.
