### ISSUE TITLE
can gendry supprot "not in"?

### ISSUE THREAD

**Issue by jingyugao** [didi/gendry#45]
I konw "not in" is ineffective, it cant optimized by index.
But I really want to use "not in".

**Comment by caibirdme** [comment]
I'll support that feature as soon as possible

**Comment by jingyugao** [comment]
> I'll support that feature as soon as possible

By the way, can gendry support different value on same key?
for example, i have a condition "I_ID in (1,2,3) and I_ID in (2,3,4) and I_ID not in (3,4)".
This sql seems stupid, however, it really happened.
NamedQuery works well in this case, but i prefer `BuildSelect`.

**Comment by caibirdme** [comment]
I suggest that you could write a function `merge(arrA, arrB []int) []int` to merge the array

**Comment by caibirdme** [comment]
@jingyugao I found that `not in` is already supported... Did you try that? Or just because you didn't find related document on README?

This is a unit test for Not In
```go

func Test_NotIn(t *testing.T) {
	where := map[string]interface{}{
		"city in":            []string{"beijing", "shanghai"},
		"age >":              35,
		"address":            IsNotNull,
		" hobbies not in   ": []string{"baseball", "swim", "running"},
		"_groupby":           "department",
		"_orderby":           "bonus desc",
	}
	table := "some_table"
	selectFields := []string{"name", "age", "sex"}
	cond, _, err := BuildSelect(table, where, selectFields)
	ass := assert.New(t)
	ass.NoError(err)
	expect := `SELECT name,age,sex FROM some_table WHERE (city IN (?,?) AND hobbies NOT IN (?,?,?) AND age>? AND address IS NOT NULL) GROUP BY department ORDER BY bonus DESC`
	ass.Equal(expect, cond)
}
```

**Comment by jingyugao** [comment]
=== RUN   Test_NotIn
--- FAIL: Test_NotIn (0.00s)
    /Users/gao/Code/bigview/server/handler_bigview_user_move_test.go:90: 
        	Error Trace:	handler_bigview_user_move_test.go:90
        	Error:      	Received unexpected error:
        	            	[builder] unsupported operator
        	Test:       	Test_NotIn
    /Users/gao/Code/bigview/server/handler_bigview_user_move_test.go:92: 
        	Error Trace:	handler_bigview_user_move_test.go:92
        	Error:      	Not equal: 
        	            	expected: "SELECT name,age,sex FROM some_table WHERE (city IN (?,?) AND hobbies NOT IN (?,?,?) AND age>? AND address IS NOT NULL) GROUP BY department ORDER BY bonus DESC"
        	            	actual  : ""
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-SELECT name,age,sex FROM some_table WHERE (city IN (?,?) AND hobbies NOT IN (?,?,?) AND age>? AND address IS NOT NULL) GROUP BY department ORDER BY bonus DESC
        	            	+
        	Test:       	Test_NotIn
FAIL
ok  	code.yunzhanghu.com/be/bigview/server	0.016s
Success: Tests passed.

**Comment by jingyugao** [comment]
maybe my version is too old.
It's gendry@v0.0.0-20190308015720-ea1a1e605683

**Comment by jingyugao** [comment]
Thanks,after updating,it works.

**Comment by caibirdme** [comment]
Use v1.0.x
