### ISSUE TITLE
支持条件或值为原生SQL的类型吗？

### ISSUE THREAD

**Issue by hookover** [didi/gendry#50]
如：
update set a = a+1 where id=(select max(id) from tb)
insert into tb(id,score) values(1, case when now() > 0 then 1 else 0 end)

怎么写?

**Comment by caibirdme** [comment]
不支持哈，gendry只支持生成简单sql。我们也不推荐在生产环境使用orm或者sql builder生成复杂sql，因为你自己手写都觉得sql很复杂了，用了orm或者sql builder之后你真的还能知道生成的sql到底长什么样吗？
所以我们建议在复杂sql的情况下，使用`builder.NamedQuery`，它能帮你节约一些拼接`where in (?,?,?....)`的时间

**Comment by hookover** [comment]
> 不支持哈，gendry只支持生成简单sql。我们也不推荐在生产环境使用orm或者sql builder生成复杂sql，因为你自己手写都觉得sql很复杂了，用了orm或者sql builder之后你真的还能知道生成的sql到底长什么样吗？
> 所以我们建议在复杂sql的情况下，使用`builder.NamedQuery`，它能帮你节约一些拼接`where in (?,?,?....)`的时间

但我的要做的项目是不能提前知道表名称、表类型、表结构的，所以不能提前定义模型。
但又会有类似的需求

**Comment by caibirdme** [comment]
@hookover 因为gendry默认会把map[string]interface{}{k:v,}中的v用?代替，生成的sql就是`select * from tb where a = ?`（为了防注入必须prepare）。本质上我可以支持一个类似你说的Raw类型，当识别到是Raw类型时我就什么都不做。可以是可以，但这并不解决问题。如果你的Raw是这样的呢？
```go
map[string]interface{}{
  "id >": builder.Raw("select id from user where city in 值1,值2,...")
}
```
值怎么填?
进一步你可能希望能够这样：
```go
map[string]interface{}{
  "id >": builder.Raw("select id from user where city in {{cities}} and age < {{age}}", map[string]interface{}{
                                                                     "cities": []string{"Beijing", "Chengdu",},
                                                                     "age": 27,  
                                                                     }),
}
```
但是这依旧不解决问题，因为你说外层的sql都无法确定，那内层的子查询几乎也无法确定，所以实际上用处不大。
因此还是建议能够用NamedQuery手写，实在不行先用BuildSelect把外层的build好，然后自己找准位置去replace

**Comment by hookover** [comment]
属性的值可以增加两种类型，一种是 builder ,另一种是 Raw
遇到 builder 的时候，解析为子sql语句，这样一来你甚至可以无限嵌套下去
遇到Raw的时候相当于原生语句

再增加这两个功能的话，应该可以实现对绝大部分复杂SQL的构建

**Comment by caibirdme** [comment]
谢谢，确实是一个比较好的建议。不过基于目前的代码架构，这个改动挺大。后续我们会考虑这个feature的
