### ISSUE TITLE
bug:SQL Injection Attack in "_orderby".

### ISSUE THREAD

**Issue by jingyugao** [didi/gendry#51]
```
func main() {
	where := map[string]interface{}{
		"_orderby": "I_ID DESC",
	}
	qry, arg, _ := builder.BuildSelect("b_dealers", where, []string{"I_ID"})
	fmt.Println(qry, arg)
       // SELECT I_ID FROM b_dealers ORDER BY I_ID DESC []
}
```
compare to raw sql.
there is SQL Injection Attack in "_orderby".

![B726F84D1B7CF396DE7B458111471E87](https://user-images.githubusercontent.com/16934055/61759279-997c4c00-adfa-11e9-8c4b-f8b5de5ad49e.jpg)

**Comment by caibirdme** [comment]
It is a problem. The reason I didn't convert value of `_orderby` and `_groupby` into `?` is that I thought people should know exactly about these values in advance. But the truth is that sometimes it's hard to say. So I will fix it as soon as possible

**Comment by caibirdme** [comment]
@jingyugao See the lastest release v1.3.0. Fixed this bug and did some optimizations

**Comment by caibirdme** [comment]
I read the mysql manual deeply and found that, `order by` and `group by` cannot be set as placeholder, because they're not the `data value`, they're part of the sql. MySQL cannot prepare a sql without knowing how to order and how to group in advance.

**Comment by jingyugao** [comment]
> I read the mysql manual deeply and found that, `order by` and `group by` cannot be set as placeholder, because they're not the `data value`, they're part of the sql. MySQL cannot prepare a sql without knowing how to order and how to group in advance.

You just need to add a comma between sortField and sortKind.

**Comment by jingyugao** [comment]
`SELECT I_ID FROM tb ORDER BY ? ?`  is error.
`SELECT I_ID FROM tb ORDER BY ?,?` is ok,

**Comment by jingyugao** [comment]
I'm sorry for this bad issue.
Mysql will ingore "order by" with bind var.Thank a lot.
