### ISSUE TITLE
是否能支持外键

### ISSUE THREAD

**Issue by Colstuwjx** [didi/gendry#52]
类似ORM里面loadRelated方法那样，gendry是否可以加载外键字段关联表的数据查询？或者这块使用方式有啥建议吗？

**Comment by caibirdme** [comment]
不支持外键。关联查询属于符合查询，需要连表查，这个时候最好还是自己写sql。即使使用ORM，涉及到多表查询，还通过外键关联时，你很可能不知道最终的sql长什么样（当然你也可以不在乎…）。不过从可维护性的角度来说，我个人还是建议你这种复杂sql还是用NamedQuery来写手。至于外键，通常情况下我不建议使用物理外键，因为随着数据量的增加，你的数据库可能分布在多节点不同实例上，这时候没法物理外键了。逻辑外键的话，可能需要加上注释来表明表之间的关系

**Comment by Colstuwjx** [comment]
明白了！
