### ISSUE TITLE
嵌套结构体无法读取

### ISSUE THREAD

**Issue by Colstuwjx** [didi/gendry#53]
如下结构体：

```
type ModelMeta struct {
	ID    int       `json:"id" ddb:"id"`
	Ctime time.Time `json:"ctime" ddb:"ctime"`
	Mtime time.Time `json:"mtime" ddb:"mtime"`
}


type App struct {
        ModelMeta
	Project string    `json:"project" ddb:"project"`
	Name    string    `json:"name" ddb:"name"`
}
```

查询时候拿不到数据，将嵌套去掉的话则是OK的

**Comment by caibirdme** [comment]
问题出在这里：
```go
type App struct {
        ModelMeta   // 这里你也需要定义tag `ddb:"you name it"`
	Project string    `json:"project" ddb:"project"`
	Name    string    `json:"name" ddb:"name"`
}
```

**Comment by Colstuwjx** [comment]
这个本身app的数据体是类似这样的：

```
{
    id: 1,
    ctime: "2019-07-24T16:03:39+08:00",
    mtime: "2019-07-24T16:03:39+08:00",
    project: "xxx",
    name: "xxx"
}
```

ModelMeta如果定义tag的话，岂不是多了一层

**Comment by caibirdme** [comment]
因为你的某个字段如果没定义ddb的tag，gendry就会认为那个字段和表数据无关，所以你的结构体定义必须跟表结构保持一致：
```go
type App struct {
        ID int `ddb:"id"`
        CTime time.TIme `ddb:"ctime"`
        // ... 
	Project string    `json:"project" ddb:"project"`
	Name    string    `json:"name" ddb:"name"`
}
```
然后再根据需要把能和表结构映射上的对象，转换成你逻辑上需要的对象。

嵌套结构体一般上只适用于字段值是json的情况，比如你在表里把学生考试成绩类型设置为json，或者类型就是varchar但里面存的是json字符串：
```
{
  "name": "tom",
  "exam_result": {"math": 100, "chinese": 98}
}
```
这时候你就可以通过定义嵌套结构体来Scan，如果某个字段类型是pb的二进制，你也可以自己实现`ByteUnmarshaler`接口来自定义怎么Unmarshal

**Comment by Colstuwjx** [comment]
Go里面的`embedded struct`，个人理解应该字段就是继承自源结构体了，常见的ORM，比如beego实现的ORM，也是支持这样的嵌套结构体的数据序列化反序列化的，是否可以考虑支持这样的场景？

这个可能跟显式的某个字段是JSON\PB的情况还不太一样，它其实就是app的一组字段，不是多加了一层的JSON

**Comment by caibirdme** [comment]
如果要支持自动绑定embedded struct，那下面这样的结构体也要支持：

```go
// {"id": 1, "col_e": 20}
type Table struct {
  ID int `ddb:"id"`
  A struct {
    B struct {
      C struct {
        D struct {
          E int `ddb:"col_e"`
        }
      }
    }
  }
}
```
我个人感觉这个实际上还是对象功能职责没有分清楚。实际中我还是推荐，针对每个表，专门写一个与其对应的结构体。Scan操作的都是这类结构体。之后，你可以进行各种领域建模和抽象，这个结构体中哪几个字段属于UserInfo，哪些属于MetaData，然后再定义对应的结构体把表数据转换成你期望的对象。这样或许稍微有点麻烦，但是结构很清晰。
至于为每个表专门写对应的结构体，其实有工具可以根据你的数据库自动生成，你可以看看文档最后的链接

**Comment by Colstuwjx** [comment]
soga！感谢大佬指点！
