### ISSUE TITLE
有没有考虑把 这个 聚合 sql2mongo 和 sql2es?

### ISSUE THREAD

**Issue by tx991020** [didi/gendry#54]
正打算基于这个做一个 sql2mongo,和 sql2es 的东西。 统一 mysql,mongo,es 三中数据库，屏蔽底层数据库。 前端只要传 map 就能实现 单表 万能查询。 请问这种东西 滴滴 是否 已经有了?

**Comment by caibirdme** [comment]
据我所知是没有的，不过你说的感觉应该也是个复杂的项目啊

**Comment by tx991020** [comment]
因为我现在要做个通用的es查询接口给前端用，前端传map过来。 所以打算先用这个转sql，再sql2es.

**Comment by caibirdme** [comment]
可以，我同事 @cch123 已经开发过一个[sql2es](https://github.com/cch123/elasticsql)，你可以看看 能否派上用场
