### ISSUE TITLE
Go beginner confused about the parameter ctx context.Context for AggregateQuery

### ISSUE THREAD

**Issue by john-zed** [didi/gendry#58]
Hi, I am Go beginner and confused about the parameter ctx context.Context for function AggregateQuery.
Could you please provide a example and explain why using context.Context?
Thanks.

**Comment by caibirdme** [comment]
`context.Context` is a mechanism to control goroutines in Go, it's not gendry specific, most of Go functions require you to pass a `context.Context` as a parameter. By `context.Context`, you can set the timeout of a operation, you can cancel a time-consuming operation when some events happen... For more details, I suggest that you can ask for Google or Golang offical document. It's part of the language,  not invented by gendry.
but In general, when you don't know what `context.Context` is, or when you don't know how to set the its value, it usually means that you don't need it. If so, you can just pass a `context.TODO()` which will create an empty `context.Context`:
```go
builder.AggregateQuery(context.TODO(), //...)
```
What's more, `context.WithTimeout` cannot control the internal mysql operation timeouts, like readtimeout or writetimeout etc... If you're curious about context.Context, you'd better learn it from google, and it's beyond gendry's scope

**Comment by john-zed** [comment]
Thanks so much for your patience.

**Comment by caibirdme** [comment]
u r welcome
