### ISSUE TITLE
数据库字段为自带关键字时插入报错

### ISSUE THREAD

**Issue by zt3862266** [didi/gendry#69]
表结构如下：
CREATE TABLE `gateway` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(64) NOT NULL DEFAULT '' COMMENT '网关名',
  `desc` varchar(256) NOT NULL DEFAULT '' COMMENT '描述',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否已删除, 0：否、1：是',
  `create_time` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '记录添加时间',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 COMMENT='网关配置表';

使用gendry拼接的sql类似这样：

 [exec sql] sql: INSERT INTO gateway (create_time,deleted,desc,name) VALUES (?,?,?,?), args: [31 0 测试嘿嘿哈哈哈1053 gateway1053]

注意： 这里的desc是数据库关键字，造成报错，建议在字段前后使用``包裹

**Comment by caibirdme** [comment]
不加``当时主要考虑的是可以额外留一点可以trick的空间，来更改sql语句，比如说 可以把 field的[]string{"*"}写成[]string{"SQL_NO_CACHE *"}，这样最终构建的sql就是 `select SQL_NO_CACHE * from xxx where yyy`，这样可以强制mysql不使用缓存，包括where中的字段，也可以使用mysql自带的函数。主要是这么一个考虑。

谢谢你的建议，我们会思考一下怎样改进，也建议尽量避免使用软件自身的保留字

**Comment by nlimpid** [comment]
插入和读取的语法不同，以最简单的插入为例，其实col_name是不允许修饰，所以非select的builder都应该加``


``` 
INSERT [LOW_PRIORITY | DELAYED | HIGH_PRIORITY] [IGNORE]
    [INTO] tbl_name
    [PARTITION (partition_name [, partition_name] ...)]
    [(col_name [, col_name] ...)]
    { {VALUES | VALUE} (value_list) [, (value_list)] ...
      |
      VALUES row_constructor_list
    }
    [AS row_alias[(col_alias [, col_alias] ...)]]
    [ON DUPLICATE KEY UPDATE assignment_list]
```

[1] https://dev.mysql.com/doc/refman/8.0/en/insert.html

**Comment by baozh** [comment]
这个解决了吗？我也遇到这个问题。用到了mysql关键字做字段名，查询失败。有什么方法解决吗？

**Comment by caibirdme** [comment]
> 这个解决了吗？我也遇到这个问题。用到了mysql关键字做字段名，查询失败。有什么方法解决吗？

@baozh 目前推荐暂时不要用数据库保留字做字段名, 下周会上一个版本解决这个问题

**Comment by flyEagle2010** [comment]
另外下周的版本能不能加个debug模式把sql打出来方便调试

**Comment by caibirdme** [comment]
@zt3862266 @nlimpid @baozh 关于这个问题, 我写了[一个wiki](https://github.com/didi/gendry/wiki/gendry-2%E7%9A%84%E4%B8%80%E4%BA%9B%E6%83%B3%E6%B3%95)来解释, 非常希望大家可以抽时间看一看. 也很希望得到大家阅后的反馈
目前来看, 短期内是没办法直接解决这个问题, 因为这是个breaking change.
对于和关键字冲突的case, 我提供两个解决方法:
1. 自己加上\`, 比如:
```
where := map[string]interface{}{"`select`": "football", "`age` >": 10}
```
2. 使用NamedQuery:
```
builder.NamedQuery("select * from `tb` where `select`={select}", map[string]interface{}{"`select`": "football",})
```
