### ISSUE TITLE
How to build complex query when param is uncertainty?

### ISSUE THREAD

**Issue by nunchaju** [didi/gendry#7]
## example
``` 
select * from tb where name={{name}} and id in (select uid from anothertable where score in {{m_score}})
```
if 'm_score' is empty, then the sql change to 

``` 
select * from tb where name={{name}}
```
so is there any method to take out of whole sub query when the param is null.

**Comment by caibirdme** [comment]
It's better to use two different sqls to meet your needs.
Sql should be `intuitive`, people may get puzzled If you write one sql but another is executed.
`WYSIWYG` (what you see is what you get) is very important

```go
if isEmptySlice(m_score) {
   build(sql1, params...)
} else {
   build(sql2, params...)
}
```

**Comment by nunchaju** [comment]
@caibirdme I see, so the following is more like a question than a issue

if the params is more than two, the combination will be much.

example:

``` 
select * from tb where name={{name}} and age > {{age}} and id in (select uid from anothertable where score in {{m_score}}) and city in (select city from tb2 where tb2id = {{city}}
```

the judgement condition will be like this:
``` 
if name == "" && age != 0 && ! isEmptySlice(m_score) && city != "" {
    build(sql1, params...)
} else if name != "" && age != 0 && ! isEmptySlice(m_score) && city != "" {
    build(sql2, params...)
...// maybe n*n
}
```

**Comment by caibirdme** [comment]
Isn't it weird that you want to search the information of someone whose name={{name}}  but the {{name}} is an empty string? If you ignore this comparison, it's very likely to be wrong.
Queries with different conditions are absolutely different, they should be separated

**Comment by xurwxj** [comment]
@nunchaju @caibirdme i forked to add a DynQuery for dynamic sql generate.

https://github.com/xurwxj/gendry
