### ISSUE TITLE
Support offset

### ISSUE THREAD

**Issue by mayowa** [didi/gendry#70]
Hi,
I can't find any support for the offset clause

```
select 
  * 
from 
  "table" 

where 
  age > 30 

offset 20 
limit 10
```

Do you have reasons for not supporting this or is this an omission .

Thanks

**Comment by caibirdme** [comment]
Seeing as `limit x,y` is the same as `limit y offset x`, we just support `limit x,y`, so you can do like this
```
where := map[string]interface{}{
  "_limit": []uint{20, 10}
}
```

**Comment by mayowa** [comment]
Ah Ok! I knew I must have missed something.
Thank you.
