### ISSUE TITLE
go test fails in builder package with error: const overflows int.

### ISSUE THREAD

**Issue by cncal** [didi/gendry#72]
> $ go test
 github.com/didi/gendry/builder [github.com/didi/gendry/builder.test]
.\utils_test.go:90:48: constant 9223372036854775807 overflows int
note: module requires Go 1.13
FAIL    github.com/didi/gendry/builder [build failed]

As describe above, a panic occurs when I test the new test case. The input of [AddRow](https://github.com/DATA-DOG/go-sqlmock/blob/7d7fc89ac4d6e7994c74cf16a6cb774b0374f2f9/rows.go#L165) is actually untyped `...interface{}`, so constant `math.MaxInt64` causes a compile-time error. If `AddRow(int64(math.MaxInt64))` could be better for this case?

**Comment by caibirdme** [comment]
Do you run test on 32-bit os? can't reproduce on my macos and ubuntu and neither on the travis ci

**Comment by cncal** [comment]
windows 64-bit os.

**Comment by cncal** [comment]
Sorry, I got `GOARCH=386` from `go env`. Maybe I set it sometime.
