### ISSUE TITLE
Is it possible to add `_or` operator?

### ISSUE THREAD

**Issue by cncal** [didi/gendry#75]
`gendry` is a good tool to build SQL except for **OR** statements. Can we add a new operator to support it? Just like: 
```go
cond, vals, err := builder.BuildSelect(
     "test",
     map[string]interface{}{
          "id >": 1,
	  "_or": map[string]interface{}{
	       "foo":   2,
	       "bar >": 3,
	  },
     },
     []string{
          "foo",
     },
)
```
it equals:
```sql
SELECT `foo` FROM `test` WHERE `id` > 1 AND (`foo` = 2 OR `bar` > 3);
```

**Comment by Colstuwjx** [comment]
Relative issue: #34 .

**Comment by caibirdme** [comment]
@Colstuwjx @cncal Yes, we can. The reason I didn't support _or at the begining is that, if I support _or, it's inevitable people will write codes like this:
```go
map[string]interface{}{
  "_or": map[string]interface{}{
     "id >": 5,
     "_or": map[string]interface{}{
       "_or": map[string]interface{}{
         // ...
       }
     }
  }
}
```
And it'll soon become hard to understand.

But now, I think it's Okay. People know what they're doing. So, I will add the feature soon. Or if you like, it's welcome to send a pr for this

**Comment by Colstuwjx** [comment]
I agree that introducing nested `_OR` would make it hard to understand. Besides, We've been supported sth like this:

```
where := map[string]interface{}{
	"city in": []string{"beijing", "shanghai"},
	"score": 5,
	"age >": 35,
	"address": builder.IsNotNull,
	"_orderby": "bonus desc",
	"_groupby": "department",
}
```

if we decide to support `_OR` primitive, I suggest just take one layer, and suggest users take NamedQuery if the SQL is nested OR query. Otherwise, the `where` may grows big and hard to maintain the impl.

**Comment by Colstuwjx** [comment]
I have been proposed a draft PR #77 for this issue, Let's talk the details inside PR comments :)
