### ISSUE TITLE
使用scanner.ScanMapClose(rows) ，读取数据不能正常显示字符串

### ISSUE THREAD

**Issue by zhaoaoranke** [didi/gendry#76]
这是测试代码
	db, err = manager.New(dbName, userName, password, ip).Set(
		manager.SetCharset("utf8"),
		manager.SetAllowCleartextPasswords(true),
		manager.SetInterpolateParams(true),
		manager.SetTimeout(1*time.Second),
		manager.SetReadTimeout(1*time.Second)).Open(true)

	if err != nil {
		fmt.Printf("error=%v\n", err)
	} else {
		cond, _, _ := builder.BuildSelect("test_table", nil, nil)
		if db != nil {
			rows, _ := db.Query(cond)
			resultMap, _ := scanner.ScanMapClose(rows)
			for _,record := range resultMap {
				fmt.Printf("record==%v \n", record["name"])
			}
			data, _ := json2.Marshal(resultMap)
			fmt.Printf("data==%v \n", string(data))
		} else {
			fmt.Printf("db=%v\n", db)
		}
	}

这是打印结果
record==[229 130 178 231 132 182] 
record==[229 133 182 228 187 150] 
data==[{"age":"MA==","id":"MQ==","name":"5YKy54S2","sex":"YQ=="},{"age":"MQ==","id":"Mg==","name":"5YW25LuW","sex":"Yg=="}] 
转Json之前和之后都没有正常显示字符串，请问是什么原因呢

如果使用结构体解析读取的数据就可以正常显示字符串

**Comment by caibirdme** [comment]
@zhaoaoranke 这是golang标准库encoding/json的问题, 在Marshal一个对象时会把[]byte类型进行base64转成字符串保存. 有一个简单的例子可以实验:
```go
package main

import (
	"encoding/json"
	"fmt"
)

func main() {
	s := "hello"
	b := []byte(s)
	data := make(map[string]interface{})
	data["foo"] = b
	v, _ := json.Marshal(data)
	fmt.Println(string(v))
        // 输出: {"foo":"aGVsbG8="}
}
```
gendry文档上面有说, 如果使用ScanMap, 要自己处理json.Marshal带来的问题.
所以建议还是定义结构体来Scan, gendry内部做了处理

**Comment by zhaoaoranke** [comment]
好的 谢谢
