### ISSUE TITLE
【Q】how to scan mysql DATE_TIME into golang  time.Time

### ISSUE THREAD

**Issue by arthurkiller** [didi/gendry#80]
how to scan mysql Date_Time into golang  time.TIME

> CreateTime is int which is not AssignableBy []uint8

**Comment by caibirdme** [comment]
Actually, this is a bug. If you don't set `parseTime=true` when initialize the `sql.DB`, the mysql driver won't parse datetime type, thus it returns a []uint8 to gendry. Gendry will convert it to string or something else, but lost the case of time! Gendry should have been smarter to handle this case, and I'll fix it as soon as possible
But for now, the workaround is set `parseTime=true`

**Comment by arthurkiller** [comment]
@caibirdme 

cool, how could I set this option?

**Comment by caibirdme** [comment]
> @caibirdme
> 
> cool, how could I set this option?

Fixed

**Comment by arthurkiller** [comment]
@caibirdme Thx for your contribution. But, we have pined on a specific version, and the upgrade could be hard.

So how could I use the `parseTime=true` to work around this?

**Comment by caibirdme** [comment]
see the [example code](https://github.com/didi/gendry/tree/master/manager)

**Comment by arthurkiller** [comment]
`ApplyApp.UserID is int which is not AssignableBy []uint8`

another problem. how about this? @caibirdme

**Comment by arthurkiller** [comment]
int64 type in mysql

**Comment by arthurkiller** [comment]
@caibirdme int64

**Comment by caibirdme** [comment]
> @caibirdme int64

gendry will convert []uint8 to int automatically. I suggest that you can confirm the data in your mysql, is that data able to convert to int

**Comment by arthurkiller** [comment]
thx
