### ISSUE TITLE
Support SQL like `SELECT DISTINCT column`

### ISSUE THREAD

**Issue by Colstuwjx** [didi/gendry#92]
As the title said, could gendry support this feature?
Thanks.

**Comment by cncal** [comment]
Actually, `builder` doesn't impose a syntax restriction on `selectField`, so you can build your statement as follows:

``` golang
cond, vals, err := builder.BuildSelect(
    "test", 
     map[string]interface{}{
          "foo": "bar",
     }, 
     []string{
          "DISTINCT(`name`) AS `name`",
     },
)
```

**Comment by Colstuwjx** [comment]
Confirmed! Thanks for answering the question!

**Comment by caibirdme** [comment]
> Actually, `builder` doesn't impose a syntax restriction on `selectField`, so you can build your statement as follows:
> 
> ```go
> cond, vals, err := builder.BuildSelect(
>     "test", 
>      map[string]interface{}{
>           "foo": "bar",
>      }, 
>      []string{
>           "DISTINCT(`name`) AS `name`",
>      },
> )
> ```

@Colstuwjx Sorry for the late reply. That's why gendry doesn't automatically add \` around column field, give user the chance to use some mysql function on some field.
