### ISSUE TITLE
能支持下原生sql的查询吗

### ISSUE THREAD

**Issue by zj0395** [didi/gendry#93]
类似于 `update Table set a = a+1 where id=1` 这样的
看到在之前的一个issue里讨论过: https://github.com/didi/gendry/issues/50 ,里面说的一个是`a=a+1`的支持，另外说的是嵌套解析我是感觉不太有必要，生产环境下搞嵌套容易搞出问题
但上面那个`a=a+1`的确实也是比较常用的，这个能支持下吗？可以像`_orderby`, `_gropby`这样key里加个前缀或是在value里加个前缀用来表明这个字段不用参数化。mysql的字段命名貌似没啥限制，还得避免加的前缀和业务本身的字段名冲突
```
map[string]interface{}{
  "_raw:a": "b+1", // key里加前缀
  "_raw:a in": "(b+1, b+2)",
}
```
`insert, select, update, delete` 的 where 和 data 都支持这种原生字段最好，最常用的可能还是 update 时的`a=a+1`

**Comment by caibirdme** [comment]
嗯，我想一下怎样更适合。这个feature会导致sql注入的风险
