### ISSUE TITLE
like语句支持空值判断？

### ISSUE THREAD

**Issue by Wintic** [didi/gendry#94]
例如：
`
where := builder.OmitEmpty(map[string]interface{}{
		"I_STATUS":         params.Status,
		"CH_BIZ_ID":        params.BizId,
		"I_TYPE":           params.Type,
		"I_CONTENT_TYPE":   params.ContentType,
		"B_IS_DELETE":      constant.IsNotDelete,
		"D_CREATE_DATE >":  params.CreateBeginAt,
		"D_CREATE_DATE <=": params.CreateEndAt,
	}, []string{"I_TYPE", "I_CONTENT_TYPE", "D_CREATE_DATE >", "D_CREATE_DATE <="})

	if params.Title != "" {
		where["CH_TITLE like"] = ...
	}`

builder.OmitEmpty 无法判断空值，目前只能手动判断

**Comment by Wintic** [comment]
在模糊匹配场景的时候的问题

**Comment by caibirdme** [comment]
看你的代码示例，你需要把`"CH_TITLE like"`加到[]string{}中才行啊。
```go
where := builder.OmitEmpty(map[string]interface{}{
  "CH_TITLE like": param.Title,
  // others ...
}, []string{"CH_TITLE like"})
```

**Comment by Wintic** [comment]
> 看你的代码示例，你需要把`"CH_TITLE like"`加到[]string{}中才行啊。
> 
> ```go
> where := builder.OmitEmpty(map[string]interface{}{
>   "CH_TITLE like": param.Title,
>   // others ...
> }, []string{"CH_TITLE like"})
> ```

但是如果要使用模糊匹配的话，由于包含'%'，所以没办法OmitEmpty

**Comment by caibirdme** [comment]
@Wintic 举个例子？

**Comment by Wintic** [comment]
> @Wintic 你是说想要把 ` "x like": "%%"` 这种也过滤掉？或者举个例子看看？

是的

**Comment by caibirdme** [comment]
@Wintic 这个没法搞，case太多了，自己过滤一下吧

**Comment by Wintic** [comment]
> @Wintic 这个没法搞，case太多了，自己过滤一下吧

get
